# Generated by Django 2.2.7 on 2019-12-03 06:09

import django.core.validators
from django.db import migrations, models
import utils.file_upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_upload.avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment_sorting',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1, validators=[utils.validators.comment_sort]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to=utils.file_upload.avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
