# Generated by Django 2.2.7 on 2019-12-03 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20191203_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='subscribed_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posttagmap',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='post.Post'),
        ),
        migrations.AddField(
            model_name='posttagmap',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tag.Tag'),
        ),
    ]
